export const ErrorCode = [
  {code: 200, message: 'Success Get data'},
  {code: 201, message: 'Success Insert data'},
  {code: 202, message: 'Success Update data'},
  {code: 203, message: 'Success Delete data'},
  {code: 400, message: 'Bad Request'},
  {code: 401, message: 'Unauthorized'},
  {code: 402, message: 'PaymentRequired'},
  {code: 403, message: 'Forbidden'},
  {code: 404, message: 'NotFound'},
  {code: 405, message: 'MethodNotAllowed'},
  {code: 406, message: 'NotAcceptable'},
  {code: 407, message: 'ProxyAuthenticationRequired'},
  {code: 408, message: 'RequestTimeout'},
  {code: 409, message: 'Conflict'},
  {code: 410, message: 'Gone'},
  {code: 411, message: 'LengthRequired'},
  {code: 412, message: 'PreconditionFailed'},
  {code: 413, message: 'PayloadTooLarge'},
  {code: 414, message: 'URITooLong'},
  {code: 415, message: 'UnsupportedMediaType'},
  {code: 416, message: 'RangeNotSatisfiable'},
  {code: 417, message: 'ExpectationFailed'},
  {code: 418, message: 'ImATeapot'},
  {code: 421, message: 'MisdirectedRequest'},
  {code: 422, message: 'UnprocessableEntity'},
  {code: 423, message: 'Locked'},
  {code: 424, message: 'FailedDependency'},
  {code: 425, message: 'UnorderedCollection'},
  {code: 426, message: 'UpgradeRequired'},
  {code: 428, message: 'PreconditionRequired'},
  {code: 429, message: 'TooManyRequests'},
  {code: 431, message: 'RequestHeaderFieldsTooLarge'},
  {code: 451, message: 'UnavailableForLegalReasons'},
  {code: 500, message: 'InternalServerError'},
  {code: 501, message: 'NotImplemented'},
  {code: 502, message: 'BadGateway'},
  {code: 503, message: 'ServiceUnavailable'},
  {code: 504, message: 'GatewayTimeout'},
  {code: 505, message: 'HTTPVersionNotSupported'},
  {code: 506, message: 'VariantAlsoNegotiates'},
  {code: 507, message: 'InsufficientStorage'},
  {code: 508, message: 'LoopDetected'},
  {code: 509, message: 'BandwidthLimitExceeded'},
  {code: 510, message: 'NotExtended'},
  {code: 511, message: 'NetworkAuthenticationRequired'},
];
